### ISSUE TITLE
設定キャッシュのNote部分についての誤訳

### ISSUE THREAD

**Issue by migraine163** [laravel-ja/ja-docs-5.7#12]
https://github.com/laravel-ja/ja-docs-5.7/blob/master/translation-ja/configuration.md#%E8%A8%AD%E5%AE%9A%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5

> Note: 開発期間中にconfig:cacheコマンドを実行する場合は、設定ファイルの中で必ずenv関数だけを使用してください。設定ファイルがキャッシュされると、.envファイルはロードされなくなり、env関数の呼び出しは全てnullを返します。

> If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded and all calls to the env function will return null.

* このノートは、開発中に対する注意ではなく、デプロイ時に対する注意事項です。
* 設定ファイルの中での注意ではなく、全実装に対する注意事項です。

1文目について、大きく内容がずれていると考えられ、また正しく理解しなかった場合に大きな問題を引き起こす項目です。

### 意訳

デプロイ時に `config:cache` を実行する場合、`env` 関数は設定ファイル内のみで利用し、それ以外の場所で呼び出していないことを、必ず確認してください。設定ファイルがキャッシュされた状態になると、`.env` ファイルのロードは行われず、また全ての `env` 関数の呼び出しがnullを返すようになります。

**Comment by mikkame** [comment]
@migraine163 Hi!
同じ問題を発見してプルリク作ろうと思ったら既にIssue が挙がってたので便乗させてもらいました

5.5、5.6も同じ誤植っぽいので #13 がマージされたらそっちにも修正しに行きます

**Comment by HiroKws** [comment]
ありがとうございます。ただ、アプリが大きくなると、変化の少ない開発後期時やテスト時に設定キャッシュの利用を考える方もいらっしゃるかもしれません。そのため、「デプロイ時」と言い切ることはできませんのでこのセクションを以下のように変更します。（テスト時のキャッシュ利用に関しては、いろいろノウハウや問題があったように記憶していますが、原文から離しすぎると翻訳文の管理が面倒になります。もし、デプロイ時だけに限定したほうがわかりやすいとお考えであれば、お手数ですが原文に対してプルリクをお願いします。）

----------------

## 設定キャッシュ

アプリケーションをスピードアップさせるために、全設定ファイルを一つのファイルへまとめる、`config:cache` Artisanコマンドを使ってください。これによりアプリケーションの全設定ファイルのオプションが、単一のファイルに結合され、フレームワークが素早くロードできるようになります。

一般的には、本番環境へのデプロイ作業の一環として、`php artisan config:cache`コマンドを実行すべきでしょう。アプリケーションの開発期間中は設定が頻繁に変更されることも多いので、ローカルでの開発中にこのコマンドを実行してはいけません。

> {note} 開発過程の一環として`config:cache`コマンド実行を採用する場合は、必ず`env`関数を設定ファイルの中だけで使用してください。設定ファイルがキャッシュされると、`.env`ファイルはロードされなくなり、`env`関数の呼び出しは全て`null`を返します。

------------------------------

メンテ期間が終了した５．６は通常更新しませんが、５．５、５．６，５，７まとめてこちらで同一内容に変更します。

**Comment by migraine163** [comment]
deployment process の範囲を過小評価される可能性を恐れてデプロイ時という意訳を行っていましたので、取り違えの発生しづらい対訳となっていれば問題ないかと思います。 👍
