### ISSUE TITLE
Laravel 5.7 HTTPリクエスト 誤植報告

### ISSUE THREAD

**Issue by MrKKKKK** [laravel-ja/ja-docs-5.7#17]
[Laravel 5.7 HTTPリクエスト > アップロードファイルの取得](https://readouble.com/laravel/5.7/ja/requests.html#retrieving-uploaded-files)
> リクエスト中にファイルが存在しているかを判定するには、hadFileメソッドを使います。
> 
> if ($request->hasFile('photo')) {
>     //
> }

翻訳では「hadFile」
サンプルソースでは「hasFile」となっております。

**Comment by HiroKws** [comment]
ありがとうございました。修正いたしました。
