### ISSUE TITLE
誤植だと思ったのでよろしくお願いいたします。

### ISSUE THREAD

**Issue by nodokaodayaka** [laravel-ja/ja-docs-5.7#2]
下記のURLで「Laravel 5.7 アップグレードガイド」項目のキャッシュについて
うまく翻訳が「Cacキャッシュhe」となっていました。
https://readouble.com/laravel/5.7/ja/upgrade.html

細かくて大変申し訳ありません。

**Comment by HiroKws** [comment]
ありがとうございます。
